---
- name: Create ~/.config/git
  file:
    dest: "~/.config/git"
    state: directory

- name: Link gitconfig
  file:
    src: "{{ role_path }}/files/gitconfig"
    dest: "~/.config/git/config"
    state: link

- name: Link gitignore
  file:
    src: "{{ role_path }}/files/gitignore"
    dest: "~/.config/git/ignore"
    state: link
