---
- name: Remove Unwanted Repos
  become: true
  yum_repository:
    name: "{{ item }}"
    state: "absent"
  loop:
    - "fedora-cisco-openh264"

- name: Remove Unwanted Packages
  become: true
  dnf:
    name:
      - "abrt-*"
      - "cheese"
      - "gnome-boxes"
      - "gnome-logs"
      - "gnome-maps"
      - "gnome-photos"
      - "gnome-software"
      - "gnome-tour"
      - "libreoffice-*"
      - "rhythmbox"
      - "simple-scan"
      - "totem"
    state: "absent"
