---
- name: Add RPM Fusion Repo
  become: true
  dnf:
    name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
    disable_gpg_check: true
    state: "present"

- name: Update Packages
  become: true
  dnf:
    name: "*"
    state: "latest"

- name: Remove Unwanted Packages and Repos
  become: true
  dnf:
    name:
      - "fedora-repos-modular"
      - "abrt-*"
      - "cheese"
      - "gnome-boxes"
      - "gnome-connections"
      - "gnome-clocks"
      - "gnome-logs"
      - "gnome-maps"
      - "gnome-photos"
      - "gnome-software"
      - "rhythmbox"
      - "simple-scan"
      - "totem"
    state: "absent"
