---
- name: Remove Unwanted Repos
  become: true
  file:
    path: "/etc/yum.repos.d/{{ item }}.repo"
    state: "absent"
  loop:
    - "fedora-cisco-openh264"
    - "fedora-modular"
    - "fedora-updates-modular"
    - "fedora-updates-testing-modular"
    - "fedora-updates-testing"

- name: Remove Unwanted Packages
  become: true
  dnf:
    name:
      - "abrt-*"
      - "cheese"
      - "gnome-boxes"
      - "gnome-logs"
      - "gnome-maps"
      - "gnome-photos"
      - "gnome-software"
      - "gnome-tour"
      - "libreoffice-*"
      - "rhythmbox"
      - "simple-scan"
      - "totem"
    state: "absent"
