---
- name: Add RPM Fusion Repo
  become: true
  dnf:
    name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
    disable_gpg_check: true
    state: "present"

- name: Update Packages
  become: true
  dnf:
    name: "*"
    state: "latest"

- name: Remove Unwanted Repos
  become: true
  file:
    path: "/etc/yum.repos.d/{{ item }}.repo"
    state: "absent"
  loop:
    - "fedora-cisco-openh264"
    - "fedora-modular"
    - "fedora-updates-modular"
    - "fedora-updates-testing-modular"
    - "fedora-updates-testing"

- name: Remove Unwanted Packages
  become: true
  dnf:
    name:
      - "abrt-*"
      - "cheese"
      - "gnome-boxes"
      - "gnome-clocks"
      - "gnome-logs"
      - "gnome-maps"
      - "gnome-photos"
      - "gnome-software"
      - "gnome-tour"
      - "libreoffice-*"
      - "rhythmbox"
      - "simple-scan"
      - "totem"
    state: "absent"
