---
- hosts: localhost
  connection: local
  remote_user: "{{ localuser }}"
  vars:
    user: "{{ localuser }}"
  roles:
    - packages
    - bat
    - fish
    - git
    - nano
    - starship
    - tilix
    - wget