---
- hosts: localhost
  connection: local
  remote_user: "{{ localuser }}"
  vars:
    user: "{{ localuser }}"
  roles:
    - { role: packages, tags: ['packages'] }
    - { role: bat, tags: ['bat'] }
    - { role: fish, tags: ['fish'] }
    - { role: git, tags: ['git'] }
    - { role: nano, tags: ['nano'] }
    - { role: starship, tags: ['starship'] }
    - { role: tilix, tags: ['tilix'] }
    - { role: wget, tags: ['wget'] }