---
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  roles:
    # - "dnf"
    # - "cli"
    # - "desktop_files"
    # - "fonts"
    # - "tilix"
    - "gnome"