---
- hosts: localhost
  connection: local
  remote_user: "{{ localuser }}"
  gather_facts: no
  vars:
    user: "{{ localuser }}"
  roles:
    - bat
    - fish
    - git
    - nano
    - wget
    - starship