---
- name: Add VSCodium GPG key
  become: true
  rpm_key:
    state: present
    key: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg

- name: Add VSCodium Repo
  become: true
  yum_repository:
    name: "gitlab.com_paulcarroty_vscodium_repo"
    description: "VSCodium Repo"
    file: "vscodium"
    baseurl: "https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/rpms/"
    enabled: yes
    gpgcheck: yes

- name: Install VSCodium
  become: true
  package:
    name: "codium"
    state: present

- name: Install Extensions
  shell:
    cmd: codium --install-extension "{{ item }}"
    creates: "~/.vscode-oss/extensions/{{ item }}-*"
  with_items:
    - dracula-theme.theme-dracula

- name: Link Keybindings
  file:
    src: "{{ role_path }}/files/keybindings.json"
    dest: "~/.config/VSCodium/User/keybindings.json"
    state: link

- name: Link Settings
  file:
    src: "{{ role_path }}/files/settings.json"
    dest: "~/.config/VSCodium/User/settings.json"
    state: link