---
- name: Add codium gpg key
  become: true
  rpm_key:
    state: present
    key: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg

- name: Add codium Repo
  become: true
  yum_repository:
    name: "gitlab.com_paulcarroty_vscodium_repo"
    description: "VSCodium Repo"
    file: "vscodium"
    baseurl: "https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/rpms/"
    enabled: yes
    gpgcheck: yes

- name: Install codium
  become: true
  package:
    name: "codium"
    state: present

- name: Install extensions
  shell:
    cmd: codium --install-extension "{{ item }}"
    creates: "~/.vscode-oss/extensions/{{ item }}-*"
  with_items:
    - dracula-theme.theme-dracula
    - bmalehorn.vscode-fish
    - EditorConfig.EditorConfig
    - vscjava.vscode-java-debug
    - bungcip.better-toml
    - samuelcolvin.jinjahtml
    - redhat.vscode-xml
    - redhat.vscode-yaml
    - redhat.java
    - Zignd.html-css-class-completion
    - PKief.material-icon-theme
    - ritwickdey.LiveServer
    - adpyke.codesnap
    - ms-python.python
    - timonwong.shellcheck
    - rust-lang.rust

- name: Link keybindings
  file:
    src: "{{ role_path }}/files/keybindings.json"
    dest: "~/.config/VSCodium/User/keybindings.json"
    state: link

- name: Link settings
  file:
    src: "{{ role_path }}/files/settings.json"
    dest: "~/.config/VSCodium/User/settings.json"
    state: link