---
- name: Create Config Directory
  file:
    path: "~/.config/VSCodium/User"
    state: directory

- name: Copy Configs
  copy:
    src: "{{ item }}"
    dest: "~/.config/VSCodium/User/{{ item }}"
  loop:
    - "keybindings.json"
    - "settings.json"

- name: Add VSCodium GPG Key
  become: true
  rpm_key:
    key: "https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg"
    state: present

- name: Add VSCodium Repo
  become: true
  yum_repository:
    name: "gitlab.com_paulcarroty_vscodium_repo"
    description: "VSCodium Repo"
    file: "vscodium"
    baseurl: "https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/rpms/"
    enabled: true
    gpgcheck: true

- name: Install VSCodium
  become: true
  dnf:
    name: "codium"
    state: present

- name: Install Extensions
  shell:
    cmd: "codium --install-extension {{ item }}"
    creates: "~/.vscode-oss/extensions/{{ item }}-*"
  loop:
    - "mads-hartmann.bash-ide-vscode"
    - "samuelcolvin.jinjahtml"
    - "timonwong.shellcheck"
    - "redhat.vscode-yaml"
    - "redhat.vscode-xml"
    - "prince781.vala"
    - "efoerster.texlab"
    - "coolbear.systemd-unit-file"
    - "mrmlnc.vscode-scss"
    - "matklad.rust-analyzer"
    - "laurenttreguier.rpm-spec"
    - "lextudio.restructuredtext"
    - "redhat.vscode-commons"
    - "ms-python.python"
    - "ms-pyright.pyright"
    - "asabil.meson"
    - "pkief.material-icon-theme"
    - "bierner.markdown-preview-github-styles"
    - "redhat.java"
    - "mathiasfrohlich.kotlin"
    - "julialang.language-julia"
    - "zignd.html-css-class-completion"
    - "justusadam.language-haskell"
    - "haskell.haskell"
    - "hashicorp.terraform"
    - "golang.go"
    - "bmalehorn.vscode-fish"
    - "editorconfig.editorconfig"
    - "vscjava.vscode-java-debug"
    - "webfreak.code-d"
    - "adpyke.codesnap"
    - "llvm-vs-code-extensions.vscode-clangd"
    - "muhammad-sammy.csharp"
    - "bungcip.better-toml"
    - "dcasella.monokai-plusplus"