---
- name: Create Config Directory
  file:
    path: "~/.config/VSCodium/User"
    state: directory

- name: Copy Configs
  copy:
    src: "{{ item }}"
    dest: "~/.config/VSCodium/User/{{ item }}"
  loop:
    - "keybindings.json"
    - "settings.json"

- name: Add VSCodium GPG Key
  become: true
  rpm_key:
    key: "https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg"
    state: present

- name: Add VSCodium Repo
  become: true
  yum_repository:
    name: "gitlab.com_paulcarroty_vscodium_repo"
    description: "VSCodium Repo"
    file: "vscodium"
    baseurl: "https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/rpms/"
    enabled: true
    gpgcheck: true

- name: Install VSCodium
  become: true
  dnf:
    name: "codium"
    state: present
