---
- name: Link .desktop file to hide apps
  file:
    src: "{{ role_path }}/files/hidden.desktop"
    dest: "~/.local/share/applications/{{ item }}.desktop"
    state: link
  with_items:
    - assistant
    - avahi-discover
    - bssh
    - bvnc
    - cmake-gui
    - designer
    - electron
    - electron9
    - firewall-config
    - htop
    - java-java-openjdk
    - jconsole-java-openjdk
    - jshell-java-openjdk
    - julia
    - linguist
    - lstopo
    - micro
    - mpv
    - nm-connection-editor
    - org.bpython-interpreter.bpython
    - org.gnome.Sysprof3
    - qdbusviewer
    - qv4l2
    - qvidcap
    - ranger
    - vim
    - winetricks
    - xdvi
    - zenmap-root
    - zenmap
