---
- name: Set app picker view
  dconf:
    key: "/org/gnome/shell/app-picker-view"
    value: "1"
    state: present

- name: Set favorite apps
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['firefox.desktop', 'steam.desktop', 'code-oss.desktop', 'com.gexperts.Tilix.desktop', 'org.gnome.Nautilus.desktop']" # yamllint disable-line
    state: present

- name: Configure workspaces on primary monitor
  dconf:
    key: "/org/gnome/shell/overrides/workspaces-only-on-primary"
    value: "false"
    state: present

- name: Configure weather location
  dconf:
    key: "/org/gnome/shell/weather/locations"
    value: "[<(uint32 2, <('Ottawa', 'CYOW', true, [(0.79092504517986117, -1.3206324731601402)], [(0.7926703744318554, -1.3212142437597076)])>)>]" # yamllint disable-line
    state: present

- name: Set window switcher app icon mode
  dconf:
    key: "/org/gnome/shell/window-switcher/app-icon-mode"
    value: "'app-icon-only'"
    state: present
