---
- name: Create ~/.config/npm
  file:
    dest: "~/.config/npm"
    state: directory

- name: Link npmrc file
  file:
    src: "{{ role_path }}/files/npmrc"
    dest: "~/.config/npm/npmrc"
    state: link
