---
- name: Install ncspot (Arch Linux)
  aur:
    name: "ncspot"
    skip_installed: true
    use: "paru"
  when: ansible_distribution == "ArchLinux"

- name: Create ~/.config/ncspot
  file:
    dest: "~/.config/ncspot"
    state: directory

- name: Link config.toml
  file:
    src: "{{ role_path }}/files/config.toml"
    dest: "~/.config/ncspot/config.toml"
    state: link
