---
- name: Set desktop background
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/gnome/adwaita-timed.xml'"
    state: present

- name: Set clock format
  dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'12h'"
    state: present

- name: Configure showing weekday in clock
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-weekday"
    value: "true"
    state: present

- name: Set document font
  dconf:
    key: "/org/gnome/desktop/interface/document-font-name"
    value: "'Liberation Sans 11'"
    state: present

- name: Configure hot corners
  dconf:
    key: "/org/gnome/desktop/interface/enable-hot-corners"
    value: "false"
    state: present

- name: Set font
  dconf:
    key: "/org/gnome/desktop/interface/font-name"
    value: "'Noto Sans 11'"
    state: present

- name: Set GTK theme
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Adwaita-dark'"
    state: present

- name: Set monospace font
  dconf:
    key: "/org/gnome/desktop/interface/monospace-font-name"
    value: "'JetBrains Mono 12'"
    state: present

- name: Configure showing notification in the lock screen
  dconf:
    key: "/org/gnome/desktop/notifications/show-in-lock-screen"
    value: "false"
    state: present

- name: Set acceleration profile of mouse
  dconf:
    key: "/org/gnome/desktop/peripherals/mouse/accel-profile"
    value: "'flat'"
    state: present