---
- name: Install Tilix
  become: true
  dnf:
    name: "{{ item }}"
    state: "present"
  loop:
    - "tilix"
    - "tilix-nautilus"

- name: Uninstall GNOME Terminal
  become: true
  dnf:
    name: "{{ item }}"
    state: "absent"
  loop:
    - "gnome-terminal"
    - "gnome-terminal-nautilus"

- name: Create Scheme Directory
  file:
    dest: "~/.config/tilix/schemes"
    state: "directory"

- name: Copy Scheme
  copy:
    src: "Dracula.json"
    dest: "~/.config/tilix/schemes/Monokai-Plus.json"

- name: Configure Dconf
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value | string}}"
  loop:
    - key: "/com/gexperts/Tilix/app-title"
      value: "''"

    - key: "/com/gexperts/Tilix/session-name"
      value: "''"

    - key: "/com/gexperts/Tilix/terminal-title-show-when-single"
      value: "false"

    - key: "/com/gexperts/Tilix/use-tabs"
      value: "false"

    - key: "/com/gexperts/Tilix/profiles/list"
      value: "['2b7c4080-0ddd-46c5-8f23-563fd3ba789d']"

    - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/background-color"
      value: "'#1C1C1C'"

    - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/foreground-color"
      value: "'#F8F8F2'"

    - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/background-transparency-percent"
      value: "4"

    - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/palette"
      value: ["#272822", "#F92672", "#A6E22E", "#F4BF75", "#66D9EF", "#AE81FF", "#A1EFE4", "#F8F8F2", "#75715E", "#F92672", "#A6E22E", "#F4BF75", "#66D9EF", "#AE81FF", "#A1EFE4", "#F9F8F5"] # yamllint disable-line

    - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/font"
      value: "'JetBrains Mono 12'"

    - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/show-scrollbar"
      value: "false"

    - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/terminal-bell"
      value: "'icon'"

    - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/terminal-title"
      value: "''"

    - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/use-theme-colors"
      value: "false"
