---
- name: Install Tilix
  become: true
  dnf:
    name: "{{ item }}"
    state: "present"
  loop:
    - "tilix"
    - "tilix-nautilus"

- name: Create Scheme Directory
  file:
    dest: "~/.config/tilix/schemes"
    state: "directory"

- name: Copy Scheme
  copy:
    src: "Dracula.json"
    dest: "~/.config/tilix/schemes/Dracula.json"

- name: Configure Dconf
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - app-title:
      key: "/com/gexperts/Tilix/app-title"
      value: "''"
    - session-name:
      key: "/com/gexperts/Tilix/session-name"
      value: "''"
    - show-title:
      key: "/com/gexperts/Tilix/terminal-title-show-when-single"
      value: "false"
    - use-tabs:
      key: "/com/gexperts/Tilix/use-tabs"
      value: "false"