#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

. /usr/share/bash-completion/bash_completion

export EDITOR=/usr/bin/nano
export PROMPT_DIRTRIM=3

source ~/.bash/aliases.sh
source ~/.bash/paths.sh
source ~/.bash/prompt.sh
