---
- name: Install starship (Arch Linux)
  aur:
    name: "starship"
    skip_installed: true
    use: "yay"
  when: ansible_distribution == "ArchLinux"

- name: Install starship (Fedora)
  become: true
  package:
    name: "starship"
    state: present
  when: ansible_distribution == "Fedora"

- name: Link starship config
  file:
    src: "{{ role_path }}/files/starship.toml"
    dest: "~/.config/starship.toml"
    state: link
