---
- name: Install JetBrains Mono (Arch Linux)
  become: true
  package:
    name: "ttf-jetbrains-mono"
    state: present
  when: ansible_distribution == "ArchLinux"

- name: Install Font Awesome (Arch Linux)
  become: true
  package:
    name: "ttf-font-awesome"
    state: present
  when: ansible_distribution == "ArchLinux"

- name: Install Nerd Fonts (Arch Linux)
  become: true
  package:
    name: "ttf-nerd-fonts-symbols"
    state: present
  when: ansible_distribution == "ArchLinux"

- name: Install JetBrains Mono (Fedora)
  become: true
  package:
    name: "jetbrains-mono-fonts-all"
    state: present
  when: ansible_distribution == "Fedora"

- name: Install Font Awesome (Fedora)
  become: true
  package:
    name: "fontawesome-fonts"
    state: present
  when: ansible_distribution == "Fedora"
