---
- name: Install CLI Tools
  become: true
  dnf:
    name:
      - "bat"
      - "exa"
      - "fd-find"
      - "fish"
      - "micro"
      - "pydf"
      - "ripgrep"
      - "starship"
    state: present

- name: Create Config Directories
  file:
    dest: "{{ item }}"
    state: "directory"
  loop:
    - "~/.config/bat/themes"
    - "~/.config/fish/completions"
    - "~/.config/fish/conf.d"
    - "~/.config/fish/functions"
    - "~/.config/git"
    - "~/.config/micro/colorschemes"

- name: "Bat: Copy Config"
  copy:
    src: "bat/config"
    dest: "~/.config/bat/config"
    mode: "0644"

- name: "Bat: Copy Theme"
  copy:
    src: "bat/Dracula.tmTheme"
    dest: "~/.config/bat/themes/Dracula.tmTheme"
    mode: "0644"

- name: "Bat: Build Cache"
  shell: "bat cache --build"

- name: "Fish: Copy Completions"
  copy:
    src: "{{ item }}"
    dest: "~/.config/fish/completions/{{ item | basename }}"
  with_fileglob: "fish/completions/*"

- name: "Fish: Copy Config"
  copy:
    src: "{{ item }}"
    dest: "~/.config/fish/conf.d/{{ item | basename }}"
  with_fileglob: "fish/conf.d/*"

- name: "Fish: Copy Functions"
  copy:
    src: "{{ item }}"
    dest: "~/.config/fish/functions/{{ item | basename }}"
  with_fileglob: "fish/functions/*"

- name: "Fish: Set Users Shell"
  become: true
  user:
    name: "tryton-vanmeer"
    shell: "/usr/bin/fish"

- name: "Git: Copy Config"
  copy:
    src: "{{ item }}"
    dest: "~/.config/{{ item }}"
  loop:
    - "git/config"
    - "git/ignore"

- name: "Micro: Copy Config"
  copy:
    src: "micro/settings.json"
    dest: "~/.config/micro/settings.json"

- name: "Micro: Copy Theme"
  copy:
    src: "micro/dracula.micro"
    dest: "~/.config/micro/colorschemes/dracula.micro"

- name: "Starship: Copy Config"
  copy:
    src: "starship.toml"
    dest: "~/.config/starship.toml"

- name: "Wget: Copy Config"
  copy:
    src: "wgetrc"
    dest: "~/.config/wgetrc"
