---

- name: Install CLI Tools
  become: true
  dnf:
    name:
      - "bat"
    state: present

- name: Create Config Directories
  file:
    dest: "{{ item }}"
    state: "directory"
  loop:
    - "~/.config/bat/themes"