---

- name: Install CLI Tools
  become: true
  dnf:
    name:
      - "bat"
      - "fish"
      - "exa"
      - "pydf"
    state: present

- name: Create Config Directories
  file:
    dest: "{{ item }}"
    state: "directory"
  loop:
    - "~/.config/bat/themes"

- name: "Bat: Copy Config"
  copy:
    src: "bat/config"
    dest: "~/.config/bat/config"
    mode: "0644"

- name: "Bat: Copy Theme"
  copy:
    src: "bat/Dracula.tmTheme"
    dest: "~/.config/bat/themes/Dracula.tmTheme"
    mode: "0644"

- name: "Bat: Build Cache"
  shell: "bat cache --build"